services:
  pasty:
    image: kryptikker/pasty:1.0.0
    container_name: pasty
    restart: unless-stopped

    ports:
      - "81235:8000"

    volumes:
      - ./data/uploads:/app/uploads
      - ./data/tiny-pastebin.db:/app/tiny-pastebin.db